kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prod-rolebinding
  namespace: prod
subjects:
- kind: ServiceAccount
  name: sa-prod
  namespace: prod
roleRef:
  kind: Role
  name: prod-role
  apiGroup: rbac.authorization.k8s.io
