kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: qa-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: sa-qa
  namespace: qa
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
