kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qa-rolebinding
  namespace: qa
subjects:
- kind: ServiceAccount
  name: sa-qa
  namespace: qa
roleRef:
  kind: Role
  name: qa-role
  apiGroup: rbac.authorization.k8s.io
